// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	admin "starry/internal/handler/admin"
	surl "starry/internal/handler/surl"
	"starry/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/generate",
				Handler: admin.GenerateHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CTRMiddleWare},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/foo/:surl",
					Handler: surl.SurlHandler(serverCtx),
				},
			}...,
		),
	)
}
